name: dbt_dv
profile: tpch
version: '5.4.0'
require-dbt-version: ['>=1.0.0', '<2.0.0']
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
seed-paths:
  - seeds
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
vars:
  load_date: '1992-01-08'

models:
  dbt_dv:
    +file_format: iceberg
    raw_stage:
      +materialized: view
      +tags:
        - 'raw'
    stage:
      +materialized: table
      +tags:
        - 'stage'
      +enabled: true
    raw_vault:
      +table_format: iceberg
      +file_format: delta
      +materialized: incremental
      +tags:
        - 'raw_vault'
      hubs:
        +access: public
        +tags:
          - 'hub'
      links:
        +access: public
        +tags:
          - 'link'
      sats:
        +access: public
        +tags:
          - 'satellite'
      t_links:
        +access: public
        +tags:
          - 't_link'
flags:
  require_generic_test_arguments_property: true
