name: dbt_dv
profile: tpch
version: '5.4.0'
require-dbt-version: ['>=1.0.0', '<2.0.0']
config-version: 2

dbt-cloud: 
    project-id: 11432

analysis-paths:
  - analysis
clean-targets:
  - target
seed-paths:
  - seeds
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
vars:
  load_date: '1992-01-08'

models:
  dbt_dv:
    +file_format: delta
    raw_stage:
      +materialized: view
      +tags:
        - 'raw'
    stage:
      +materialized: table
      +tags:
        - 'stage'
      +enabled: true
    raw_vault:
      +table_format: iceberg
      +materialized: incremental
      +freshness:
        build_after:
          count: 12
          period: hour
          updates_on: all
      +tags:
        - 'raw_vault'
      hubs:
        +access: public
        +tags:
          - 'hub'
      links:
        +access: public
        +tags:
          - 'link'
      sats:
        +access: public
        +tags:
          - 'satellite'
      t_links:
        +access: public
        +tags:
          - 't_link'
flags:
  require_generic_test_arguments_property: true
